apiVersion: apps/v1
kind: Deployment
metadata:
  name: murali-flower-app-deployment
  labels:
    app: example
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: murali
  template:
    metadata:
      labels:
        app: murali
    spec: # Define the Pod behaviour
      containers:
      - name: cart-app
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "100m"
          requests:
            memory: "128Mi"
            cpu: "50m"  
        ports:
        - containerPort: 3015
--- 
# Writing Service.yml to expose the application 
apiVersion: v1
kind: Service
metadata:
  name: murali-flower-app-svc
spec:
  selector:
    app: murali
  ports:
  - port: 3016 # Service Port 
    targetPort: 3015 # Container Port 
  type: LoadBalancer   
        
